accounts/urls.py
from django.urls import path
from accounts import views,views_employer, views_jobseeker
from subscriptions.views import verify_payment,initiate_payment
from django.views.generic import TemplateView


app_name='accounts'

urlpatterns = [
   
    path('sign-up',TemplateView.as_view(template_name='accounts/signup.html',extra_context={'title': 'Register'}),name="signup"),
    path('sign-in',TemplateView.as_view(template_name='accounts/login.html',extra_context={'title': 'Signin'}),name="login"),
    path('eToken',TemplateView.as_view(template_name='accounts/eToken.html',extra_context={'title': 'eToken'}),name="eToken"),
    path('password-recovery',TemplateView.as_view(template_name='accounts/password_recovery.html',extra_context={'title': 'Password Recovery'}),name="password-recovery"),
    path('jobseeker/sign-up',TemplateView.as_view(template_name='accounts/jobseeker_signup.html',extra_context={'title': 'Jobseeker Account'}),name="jobseeker-signup"),
    path('employer/sign-up',TemplateView.as_view(template_name='accounts/employer_signup.html',extra_context={'title': 'Employer Account'}),name="employer-signup"),
    path('change-password/<int:id>', views.change_password, name='change-password'),

    #Jobseeker
    path('jobseeker/dashboard', views_jobseeker.JobSeekerHomeView.as_view(), name='jobseeker-home'),
    path('jobseeker/manage-jobs', views_jobseeker.manage_job, name='jobseeker-job-manager'),
    path('jobseeker/settings', views_jobseeker.settings, name='jobseeker-settings'),
    path('jobseeker/settings/update', views_jobseeker.update_settings, name='jobseeker-settings-update'),
    path('jobseeker/security', views_jobseeker.security, name='jobseeker-security'),
    path('jobseeker/security/password-update', views_jobseeker.update_password, name='jobseeker-password-update'),
    path('jobseeker/security/username-update', views_jobseeker.update_username, name='jobseeker-username-update'),
    path('jobseeker/notifications', views_jobseeker.notification, name='jobseeker-notification'),
    path('jobseeker/<int:pk>/delete', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/delete/', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/avater-updated', views_jobseeker.update_avater, name='jobseeker-avater-update'),
    path('jobseeker/avater-removed', views_jobseeker.remove_avater, name='jobseeker-avater-remove'),
    path('jobseeker/resume',views_jobseeker.upload_cv,name='jobseeker-upload-cv'),
    path('jobseeker/resume-update',views_jobseeker.update_cv,name='jobseeker-cv-update'),
    path('jobseeker/feedback',views_jobseeker.jobseeker_feedback,name='jobseeker-feedback'),
    path('jobseeker/feedback/sent',views_jobseeker.jobseeker_feedback_save,name='jobseeker-feedback-action'),
    
    
    #Employer
    path('employer/listing/direct', views_employer.direct_job, name='employer-direct-job'),
    path('employer/listing/featured', views_employer.indirect_job, name='employer-indirect-job'),
    path('employer/applicant/view', views_employer.applicants, name='employer-job-applicants'),
    path('employer/dashboard',views_employer.dashboard, name='employer-home'),
    path('employer/profile',views_employer.settings, name='employer-settings'),
    path('employer/profile/update',views_employer.update_settings, name='employer-settings-update'),
    path('employer/logo/update',views_employer.update_logo, name='employer-logo-update'),
    path('employer/logo/remove',views_employer.remove_logo, name='employer-logo-remove'),
    path('employer/billings', views_employer.billing, name='employer-billing'),
    path('employer/security', views_employer.security, name='employer-security'),
    path('employer/security/password/update', views_employer.update_password, name='employer-password-update'),
    path('employer/security/username/update', views_employer.update_username, name='employer-username-update'),
    path('employer/notifications', views_employer.notification, name='employer-notification'),
    path('employer/feedback',views_employer.employer_feedback,name='employer-feedback'),
    path('employer/feedback/sent',views_employer.employer_feedback_save,name='employer-feedback-action'),
    path('employer/delete', views_employer.delete_account, name='employer-delete-account'),
    path('employer/payment/initiate',initiate_payment, name='employer-initiate-payment'),
    path('<str:ref>/',verify_payment,name="verify-payment"),
    
    
    
    # actions 
    path('sign-up/do', views.signup_action, name='signup-action'),
    path('eToken-validation', views.eToken_action, name='eToken-action'),
    path('eToken/reset', views.reset_eToken_action, name='reset-eToken-action'),
    path('password/reset', views.password_recovery_action, name='password-recovery-action'),
    path('password/change', views.change_password_action, name='change-password-action'),
    path('login/do', views.login_action, name='login-action'),
    path('logout', views.logout_user_action, name='logout'),
    
    
    
    
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from accounts import views_admin

urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('subscriptions/', include('subscriptions.urls',namespace='subscriptions')),
    path('', include('main.urls',namespace='main')),
    path('', include('listings.urls',namespace='listings')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
    
    # Employer
    path('jf-admin/employers',views_admin.employer_list,name='admin-employers'),
    path('jf-admin/employers/<slug:slug>/profile', views_admin.employer_profile, name="employer-profile"),
    path('jf-admin/employers/<slug:slug>/payments', views_admin.employer_payments, name="employer-payments"),
    path('jf-admin/employers/<str:ref>/verify-a-payment', views_admin.verify_payment_page, name="verify-payment-page"),
    path('jf-admin/employers/<str:ref>/verified', views_admin.verify_payment, name="verify-payment"),
   
    
    path('jf-admin/manage/listing',views_admin.manage_job, name='admin-manage-listing'),
    path('jf-admin/manage/listing/<slug:slug>/delete',views_admin.delete_job, name='admin-delete-listing'),
    
    # Jobseekr
    path('jf-admin/jobseekers',views_admin.jobseeker_list,name='admin-jobseekers'),
    path('jf-admin/jobseekers/<slug:slug>/profile', views_admin.jobseeker_profile, name="jobseeker-profile"),
    
   
    path('jf-admin/create-newsletter', views_admin.create_newsletter, name='create-newsletter'),
    path('jf-admin/newsletter-view', views_admin.newsletter_view, name='newsletter-view'),
    path('jf-admin/send-newsletter', views_admin.newsletter_action, name='newsletter-action'),
    path('jf-admin/newsletter/<slug:slug>/view', views_admin.newsletter_update_view, name='newsletter-update-view'),
    path('jf-admin/newsletter/<slug:slug>/update',views_admin.newsletter_update_action,name='newsletter-update-action'),
    path('jf-admin/newsletter/<slug:slug>/delete',views_admin.delete_newsletter,name='admin-delete-newsletter'),
    path('jf-admin/newsletter/subscriber-view', views_admin.newsletter_subscriber_view, name='newsletter-subscriber-view'),
    path('jf-admin/newsletter/subscriber/<slug:slug>/delete',views_admin.delete_newsletter_subscriber,name='admin-delete-newsletter-subscriber'),
    
    path('jf-admin/accounts-view',views_admin.manage_user,name='admin-manage-user'),
    path('jf-admin/account/<slug:slug>/view',views_admin.manage_user_update_view,name='admin-manage-user-update-view'),
    path('jf-admin/account/<slug:slug>/update',views_admin.manage_user_update,name='admin-manage-user-update'),
    path('jf-admin/account/<slug:slug>/delete',views_admin.delete_user,name='admin-delete-user'),
    

    # Admin-utilities
    path('jf-admin-create-admin',views_admin.create_admin,name='create-admin'),
    path('jf-admim-reset-password',TemplateView.as_view(template_name = "accounts/admin/reset_password.html",extra_context={'title': 'Jobfinder-Administrator-Reset-Password'}), name='admin-reset-password-view'),
    path('jf-admin-delete-admin-account',views_admin.delete_admin_account,name='delete-admin-account'),
    path('jf-admin-delete-users-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin-reset-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin',TemplateView.as_view(template_name = "accounts/admin/login.html",extra_context={'title': 'Jobfinder-Administrator-Login'}), name='login-admin'),
    path('jf-admin/login',views_admin.login_admin_action,name='login-admin-action'),
    path('jf-admin/dashboard',views_admin.AdminHomeView.as_view(), name='admin-home'),
    path('jf-admin/password/changed',views_admin.reset_password_action,name='admin-reset-password-action'),
    path('jf-admin/logout',views_admin.logout_admin,name='logout-admin'),
    path('e-404/',TemplateView.as_view(template_name='404.html',extra_context={'title': 'E404'}),name="404"),

    
  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'accounts.views.custom_page_not_found_view'
handler500 = 'accounts.views.custom_error_view'
handler403 = 'accounts.views.custom_permission_denied_view'
handler400 = 'accounts.views.custom_bad_request_view'

listings/urls.py
from django.urls import path,include
from listings import views


app_name='listings'

urlpatterns = [
  
    
    path('', views.JobListView.as_view(), name='home'),
    path('create-job',views.create_job_View,name='job-form'),
    path('post-job',views.create_job_action,name='post-job'),
    path('<slug:slug>/', views.job_detail, name="job-detail" ),
    path('<slug:slug>/application/', views.application_form, name="application-form" ),
    path('<slug:slug>/apply/', views.apply, name="apply"),
    path('<slug:slug>/edit/', views.job_form_update_view, name="job-update" ),
    path('<slug:slug>/update/', views.update_job, name="update-job" ),
    path('<slug:slug>/delete/', views.delete_job, name="delete-job" ),
   
    
    path('search-job-location', views.search_job_by_location, name="search-job-location" ),
    path('search-job-location-keyword', views.search_job_by_location_keyword, name="search-job-location-keyword" ),
   
 
 
    path('free-job-postings', views.FreeJobPostPageView.as_view(), name='free-job-post'),
    path('featured-job-posting', views.FeaturedJobPostingPageView.as_view(), name='featured-job-posting'),
    
    
    
    

   
]

listings/forms.py
from django.utils.translation import gettext_lazy as _
from django.forms import ModelForm,Textarea
from .models import Job

class JobForm(ModelForm):
    class Meta:
        model = Job
        fields = '__all__'
        exclude=['created_by']
        widgets = {
            'description': Textarea(attrs={'cols': 40, 'rows': 5}),
            'requirements': Textarea(attrs={'cols': 40, 'rows': 5}),
            'application_mode': Textarea(attrs={'cols': 40, 'rows': 5}),   
        }
        labels = {
            'company_name': _('Company Name'),
            'email': _('Email'),
            'website': _('Website'),
            'title': _('Job Title'),
            'location': _('Location'),
            'country': _('Country'),
            'salary': _('Min-Max salary'),
            'type': _('Job Type'),
            'experience': _('Experience'),
            'description ': _('Description '),
            'requirements': _('Requirements'),
            'logo': _('Company logo'),
            'closed_at': _('Deadline'),
        }
        help_texts = {
            # 'company_name': _('Company Name'),
            # 'email': _('Email'),
            # 'website': _('Website'),
            # 'title': _('Job Title'),
            # 'location': _('Location'),
            # 'country': _('Country'),
            # 'min_salary': _('Min.Salary'),
            # 'max_salary': _('Max.Salary'),
            # 'type': _('Job Type'),
            # 'experience': _('Experience'),
            # 'description ': _('Description '),
            # 'requirements': _('Requirements'),
        }
        error_messages = {
            'name': {
                'max_length': _("This writer's name is too long."),
            },
        }
    
  

listings/templates/listings/job_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{title}}
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  {{ form }}
  <input type="submit" value="Confirm">
</form>
{% endblock %}

listings/templates/listings/jobs_by_location.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{title}}
{% endblock %}

{% block  css %} 
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{%  static 'jobya/css/bootstrap.min.css' %}" type="text/css">

    <!--Material Icon -->
    <link rel="stylesheet" type="text/css" href="{%  static 'jobya/css/materialdesignicons.min.css' %}" />

    <link rel="stylesheet" type="text/css" href="{%  static 'jobya/css/fontawesome.css' %}" />

    <!-- selectize css -->
    <link rel="stylesheet" type="text/css" href="{%  static 'jobya/css/selectize.css' %}" />

    <link rel="stylesheet" type="text/css" href="{%  static 'jobya/css/nice-select.css' %}" />

    <!-- Custom  Css -->
    <link rel="stylesheet" type="text/css" href="{%  static 'jobya/css/style.css' %}" />

{% endblock css  %}
{% block navbar %}

<nav id="navbar" class="navbar">
    <ul>
      <li class="dropdown"><a href="#"><span>Find Jobs</span> <i class="bi bi-chevron-down"></i></a>
        <ul>
          <li><a href="{% url 'listings:search-job-location' %}">Jobs by Location</a></li>
          <!--<li><a href="#">Jobs by Categories</a></li>-->
        </ul>
      </li>
      <li><a class="nav-link scrollto active" href="{% url 'accounts:employer-home' %}" style="color: #106eea;">Post Jobs</a></li>
      {% if user.is_authenticated %}
      <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}" style="color: #106eea;">Logout</a></li>
        {% if request.session.is_employer %}
        <li><a class="nav-link scrollto" href="{% url 'accounts:employer-home' %}" style="color: #8110ea;">Dashboard</a></li>
        {% elif request.session.is_jobseeker %}
        <li><a class="nav-link scrollto" href="{% url 'accounts:jobseeker-home' %}" style="color: #8110ea;">Dashboard</a></li>
        {% elif request.session.is_admin  %}
        <li><a class="nav-link scrollto" href="{% url 'accounts:admin-home' %}" style="color: #8110ea;">Dashboard</a></li>
        {% endif %}
      {% else %}
      <li><a class="nav-link scrollto" href="{% url 'accounts:login' %}">Login</a></li>
      <li><a class="nav-link scrollto" href="{% url 'accounts:signup' %}" style="color: #106eea;">Sign Up</a></li>
      {% endif %}
    </ul>
    <i class="bi bi-list mobile-nav-toggle"></i>
  </nav><!-- .navbar -->

{% endblock navbar %}
{% block content %}
        <!-- Start home -->
        <section class="bg-half page-next-level"> 
            <div class="bg-overlay"></div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="text-center text-white">
                            <h6 class="mdi:alarm-clock-multiple"></h6>
                            {% comment %} <i class="bi bi-clock-history">{{now}}</i> {% endcomment %}
                                    {% now "jS F Y H:i" %}
                            <h4 class="text-uppercase title mb-4">Up-to-Date Listings</h4>
                            
                            <!--<ul class="page-next d-inline-block mb-0">
                                <li><a href="index.html" class="text-uppercase font-weight-bold">Home</a></li>
                                <li><a href="#" class="text-uppercase font-weight-bold">Jobs</a></li> 
                                <li>
                                    <span class="text-uppercase text-white font-weight-bold">Job Listing</span> 
                                </li>
                            </ul>-->
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- end home -->
    
        <div class="container">
            <div class="home-form-position">
                <div class="row justify-content-center">
                    <div class="col-lg-10">
                        <div class="home-registration-form job-list-reg-form bg-light shadow p-4 mb-3">
                            <form class="registration-form" method="POST" action="{% url 'listings:search-job-location' %}">
                                {% csrf_token %}
                                <div class="row">
                                    <!--<div class="col-lg-4 col-md-6">
                                        <div class="registration-form-box">
                                            <i class="fa fa-briefcase"></i>
                                            <input type="text" id="exampleInputName1" name="search_comName_comTitle" class="form-control rounded registration-input-box" placeholder="Job keybords...">
                                        </div>
                                    </div>-->
                                    <div class="col-lg-8 col-md-12">
                                        <div class="registration-form-box">
                                            <i class="fa fa-location-arrow"></i>
                                            <select id="select-country" class="demo-default" name="location" required>
                                                <option value="">Location</option>
                                                {% for  state in locations  %}
                                                <option value="{{state}}">{{state}}</option>
                                                {% endfor %}
                                               
                                            </select>
                                        </div>
                                    </div>
                                    <!--<div class="col-lg-3 col-md-6">
                                        <div class="registration-form-box">
                                            <i class="fa fa-list-alt"></i>
                                            <select id="select-category" class="demo-default">
                                                <option value="">Categories...</option>
                                                <option value="4">Accounting</option>
                                                <option value="1">IT & Software</option>
                                                <option value="3">Marketing</option>
                                                <option value="5">Banking</option>
                                            </select>
                                        </div>
                                    </div>-->
                                    <div class="col-lg-4 col-md-6">
                                        <div class="registration-form-box">
                                            <input type="submit" id="submit" name="" class="submitBnt btn btn-primary btn-block" value="Search">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <!-- all jobs start -->
        <section class="section bg-light">
            <div class="container">
                {% if jobs_by_location %}
                <!--search Job-->
                
                    {% for job in jobs_by_location %}
                    <div class="col-lg-12 mt-4 pt-2">
                        <div class="job-list-box border rounded">
                            <div class="p-3">
                                <div class="row align-items-center">
                                    <div class="col-lg-2">
                                        <div class="company-logo-img">
                                            <a href="{% url 'listings:job-detail' slug=job.slug %}">
                                            <img src="{{job.logo.url}}" alt="" class="img-fluid mx-auto d-block"></a>
                                        </div>
                                    </div>
                                    <div class="col-lg-7 col-md-9">
                                        <div class="job-list-desc">
                                            <h6 class="mb-2"><a href="{% url 'listings:job-detail' slug=job.slug %}" class="text-dark">{{job.title|title|urlize}}</a></h6>
                                            <p class="text-muted mb-0"><i class="mdi mdi-bank mr-2"></i>{{job.company_name}}</p>
                                            <ul class="list-inline mb-0">
                                                <li class="list-inline-item mr-3">
                                                    <p class="text-muted mb-0"><i class="mdi mdi-map-marker mr-2"></i>{{job.address}},{{job.location}} {{job.country}}</p>
                                                </li>

                                                <li class="list-inline-item">
                                                    <p class="text-muted mb-0"><i class="mdi mdi-clock-outline mr-2"></i>{{job.created_at|timesince}} ago</p>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <div class="job-list-button-sm text-right">
                                                <span class="badge badge-success">{{job.type}}</span>

                                            <div class="mt-3">
                                                <a href="{% url 'listings:job-detail' slug=job.slug %}" class="btn btn-sm btn-primary">Apply</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <p>No Data yet - {{now}}</p>
                    {% endfor %}
                <!--End search Job-->
                {% endif %} 
    
                <!-- end row -->
                <div class="row">
                    <!-- pagination starts-->
                    <div class="col-lg-12 mt-4 pt-2">
                        <nav aria-label="Page navigation example">
                            {% if is_paginated %}
                            <ul class="pagination job-pagination mb-0 justify-content-center">
                                {% if page_obj.has_previous %}
                                <li class="page-item disabled">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">
                                        <i class="mdi mdi-chevron-double-left"></i>
                                    </a>
                                </li>
                                {% else %}
                                <li class="page-item disabled">
                                    <a class="page-link"  tabindex="-1" aria-disabled="true">
                                        <i class="mdi mdi-chevron-double-left"></i>
                                    </a>
                                </li>
                                {% endif %}
                                
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                    <li class="page-item active"><a class="page-link">{{ i }} </a></li>
                                    {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }} </a></li>
                                    {% endif %}
                                {% endfor %}


                                {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                        <i class="mdi mdi-chevron-double-right"></i>
                                    </a>
                                </li>
                                {% else %}
                                <li class="page-item">
                                    <a class="page-link">
                                        <i class="mdi mdi-chevron-double-right"></i>
                                    </a>
                                </li>
                                {% endif %}
                            </ul>
                            {% endif %}
                        </nav>
                    </div>
                    <!-- pagination end-->
                </div>
            </div>
            <!-- end containar -->
        </section>
        <!-- all jobs end -->
{% endblock %}
<!--Footer-->

{% block js %}
    <!-- javascript -->
    <script src="{% static 'jobya/js/jquery.min.js' %}"></script>
    <script src="{% static 'jobya/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'jobya/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'jobya/js/plugins.js' %}"></script>

    <!-- selectize js -->
    <script src="{% static 'jobya/js/selectize.min.js' %}"></script>

    <script src="{% static 'jobya/js/jquery.nice-select.min.js' %}"></script>

    <script src="{% static 'jobya/js/app.js' %}"></script>
{% endblock js %}