accounts/urls.py
from django.urls import path
from accounts import views,views_employer, views_jobseeker
from subscriptions.views import verify_payment,initiate_payment
from django.views.generic import TemplateView


app_name='accounts'

urlpatterns = [
   
    path('sign-up',TemplateView.as_view(template_name='accounts/signup.html',extra_context={'title': 'Register'}),name="signup"),
    path('sign-in',TemplateView.as_view(template_name='accounts/login.html',extra_context={'title': 'Signin'}),name="login"),
    path('eToken',TemplateView.as_view(template_name='accounts/eToken.html',extra_context={'title': 'eToken'}),name="eToken"),
    path('password-recovery',TemplateView.as_view(template_name='accounts/password_recovery.html',extra_context={'title': 'Password Recovery'}),name="password-recovery"),
    path('jobseeker/sign-up',TemplateView.as_view(template_name='accounts/jobseeker_signup.html',extra_context={'title': 'Jobseeker Account'}),name="jobseeker-signup"),
    path('employer/sign-up',TemplateView.as_view(template_name='accounts/employer_signup.html',extra_context={'title': 'Employer Account'}),name="employer-signup"),
    path('change-password/<int:id>', views.change_password, name='change-password'),

    #Jobseeker
    path('jobseeker/dashboard', views_jobseeker.JobSeekerHomeView.as_view(), name='jobseeker-home'),
    path('jobseeker/manage-jobs', views_jobseeker.manage_job, name='jobseeker-job-manager'),
    path('jobseeker/settings', views_jobseeker.settings, name='jobseeker-settings'),
    path('jobseeker/settings/update', views_jobseeker.update_settings, name='jobseeker-settings-update'),
    path('jobseeker/security', views_jobseeker.security, name='jobseeker-security'),
    path('jobseeker/security/password-update', views_jobseeker.update_password, name='jobseeker-password-update'),
    path('jobseeker/security/username-update', views_jobseeker.update_username, name='jobseeker-username-update'),
    path('jobseeker/notifications', views_jobseeker.notification, name='jobseeker-notification'),
    path('jobseeker/<int:pk>/delete', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/delete/', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/avater-updated', views_jobseeker.update_avater, name='jobseeker-avater-update'),
    path('jobseeker/avater-removed', views_jobseeker.remove_avater, name='jobseeker-avater-remove'),
    path('jobseeker/resume',views_jobseeker.upload_cv,name='jobseeker-upload-cv'),
    path('jobseeker/resume-update',views_jobseeker.update_cv,name='jobseeker-cv-update'),
    path('jobseeker/feedback',views_jobseeker.jobseeker_feedback,name='jobseeker-feedback'),
    path('jobseeker/feedback/sent',views_jobseeker.jobseeker_feedback_save,name='jobseeker-feedback-action'),
    
    
    #Employer
    path('employer/listing/direct', views_employer.direct_job, name='employer-direct-job'),
    path('employer/listing/featured', views_employer.indirect_job, name='employer-indirect-job'),
    path('employer/applicant/view', views_employer.applicants, name='employer-job-applicants'),
    path('employer/dashboard',views_employer.dashboard, name='employer-home'),
    path('employer/profile',views_employer.settings, name='employer-settings'),
    path('employer/profile/update',views_employer.update_settings, name='employer-settings-update'),
    path('employer/logo/update',views_employer.update_logo, name='employer-logo-update'),
    path('employer/logo/remove',views_employer.remove_logo, name='employer-logo-remove'),
    path('employer/billings', views_employer.billing, name='employer-billing'),
    path('employer/security', views_employer.security, name='employer-security'),
    path('employer/security/password/update', views_employer.update_password, name='employer-password-update'),
    path('employer/security/username/update', views_employer.update_username, name='employer-username-update'),
    path('employer/notifications', views_employer.notification, name='employer-notification'),
    path('employer/feedback',views_employer.employer_feedback,name='employer-feedback'),
    path('employer/feedback/sent',views_employer.employer_feedback_save,name='employer-feedback-action'),
    path('employer/delete', views_employer.delete_account, name='employer-delete-account'),
    path('employer/payment/initiate',initiate_payment, name='employer-initiate-payment'),
    path('<str:ref>/',verify_payment,name="verify-payment"),
    
    
    
    # actions 
    path('sign-up/do', views.signup_action, name='signup-action'),
    path('eToken-validation', views.eToken_action, name='eToken-action'),
    path('eToken/reset', views.reset_eToken_action, name='reset-eToken-action'),
    path('password/reset', views.password_recovery_action, name='password-recovery-action'),
    path('password/change', views.change_password_action, name='change-password-action'),
    path('login/do', views.login_action, name='login-action'),
    path('logout', views.logout_user_action, name='logout'),
    
    
    
    
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from accounts import views_admin

urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('subscriptions/', include('subscriptions.urls',namespace='subscriptions')),
    path('', include('main.urls',namespace='main')),
    path('', include('listings.urls',namespace='listings')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
    
    # Employer
    path('jf-admin/employers',views_admin.employer_list,name='admin-employers'),
    path('jf-admin/employers/<slug:slug>/profile', views_admin.employer_profile, name="employer-profile"),
    path('jf-admin/employers/<slug:slug>/payments', views_admin.employer_payments, name="employer-payments"),
    path('jf-admin/employers/<str:ref>/verify-a-payment', views_admin.verify_payment_page, name="verify-payment-page"),
    path('jf-admin/employers/<str:ref>/verified', views_admin.verify_payment, name="verify-payment"),
   
    
    path('jf-admin/manage/listing',views_admin.manage_job, name='admin-manage-listing'),
    path('jf-admin/manage/listing/<slug:slug>/delete',views_admin.delete_job, name='admin-delete-listing'),
    
    # Jobseekr
    path('jf-admin/jobseekers',views_admin.jobseeker_list,name='admin-jobseekers'),
    path('jf-admin/jobseekers/<slug:slug>/profile', views_admin.jobseeker_profile, name="jobseeker-profile"),
    
   
    path('jf-admin/create-newsletter', views_admin.create_newsletter, name='create-newsletter'),
    path('jf-admin/newsletter-view', views_admin.newsletter_view, name='newsletter-view'),
    path('jf-admin/send-newsletter', views_admin.newsletter_action, name='newsletter-action'),
    path('jf-admin/newsletter/<slug:slug>/view', views_admin.newsletter_update_view, name='newsletter-update-view'),
    path('jf-admin/newsletter/<slug:slug>/update',views_admin.newsletter_update_action,name='newsletter-update-action'),
    path('jf-admin/newsletter/<slug:slug>/delete',views_admin.delete_newsletter,name='admin-delete-newsletter'),
    path('jf-admin/newsletter/subscriber-view', views_admin.newsletter_subscriber_view, name='newsletter-subscriber-view'),
    path('jf-admin/newsletter/subscriber/<slug:slug>/delete',views_admin.delete_newsletter_subscriber,name='admin-delete-newsletter-subscriber'),
    
    path('jf-admin/accounts-view',views_admin.manage_user,name='admin-manage-user'),
    path('jf-admin/account/<slug:slug>/view',views_admin.manage_user_update_view,name='admin-manage-user-update-view'),
    path('jf-admin/account/<slug:slug>/update',views_admin.manage_user_update,name='admin-manage-user-update'),
    path('jf-admin/account/<slug:slug>/delete',views_admin.delete_user,name='admin-delete-user'),
    

    # Admin-utilities
    path('jf-admin-create-admin',views_admin.create_admin,name='create-admin'),
    path('jf-admim-reset-password',TemplateView.as_view(template_name = "accounts/admin/reset_password.html",extra_context={'title': 'Jobfinder-Administrator-Reset-Password'}), name='admin-reset-password-view'),
    path('jf-admin-delete-admin-account',views_admin.delete_admin_account,name='delete-admin-account'),
    path('jf-admin-delete-users-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin-reset-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin',TemplateView.as_view(template_name = "accounts/admin/login.html",extra_context={'title': 'Jobfinder-Administrator-Login'}), name='login-admin'),
    path('jf-admin/login',views_admin.login_admin_action,name='login-admin-action'),
    path('jf-admin/dashboard',views_admin.AdminHomeView.as_view(), name='admin-home'),
    path('jf-admin/password/changed',views_admin.reset_password_action,name='admin-reset-password-action'),
    path('jf-admin/logout',views_admin.logout_admin,name='logout-admin'),
    path('e-404/',TemplateView.as_view(template_name='404.html',extra_context={'title': 'E404'}),name="404"),

    
  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'accounts.views.custom_page_not_found_view'
handler500 = 'accounts.views.custom_error_view'
handler403 = 'accounts.views.custom_permission_denied_view'
handler400 = 'accounts.views.custom_bad_request_view'

accounts/forms.py
from django.forms import ModelForm
from accounts.models import *
from django.utils.translation import gettext_lazy as _


class NotificationEmployerForm(ModelForm):
    
    class Meta:
        model= Employer
        fields= ['subscribed_to_newsletter',]

        labels = {
            'subscribed_to_newsletter': _('Newsletter'),
        
            }

        
class NotificationJobSeekerForm(ModelForm):
    
    class Meta:
        model= JobSeeker
        fields= ['subscribed_to_newsletter',]
       

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    {% if title  %}
    {{title}} 
    {% else %}
    Change-Password
    {% endif %}
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer" >
  <div width="100%" class="footer-newsletter">
     <div width="100%" class="container">
       <div width="100%" class="row justify-content-center">
         <div class="col-lg-6">
           <h4>JobFinder|Reset password</h4>
           <label>Enter the 6-digit code sent to {{email_id}}.</label>
          
           <form action="{% url 'accounts:change-password-action'%}" method="POST">
               {% csrf_token %}
             <div width="100%" id="login-box">
               <div class="left">
                 <h1>Change Password</h1>
                 <input type="hidden" name='email_id' id="email_id" name="email" value={{email_id}} placeholder="E-mail" />
                 <input type="number" name='eToken' id="eToken" onKeyPress="if(this.value.length==6) return false;"  placeholder="Enter the 6-digit code" />
                 <input type="password" name='new_password' id="password" placeholder="Password" />
                 <input type="password" name='confirm_password' id="password" placeholder="Confirm Password" />
                 <button class="social-signin google" type="submit" name='submit'  id="submit" value="Submit"  style="background-color: #106eea;">Change</button>
                 <p style="font-size: 12px;">Remember password?; <a href="{% url 'accounts:login' %}">Login here</a></p>
               </div>
               <div class="right" style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
                 <div style="margin-top: 130px;">
                   <h2 style="font-size: 25px; color:#fff;">You are welcome!</h2>
                   <p style="font-size: 18px; color:#fff;">Feel free to signup with us</p> 
                 </div>
               </div>
           </form>
         </div>
       </div>
     </div>
   </div>
 </div>
 
{% endblock%}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/eToken.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    Verification page 
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer"  >
    <div width="100%" class="footer-newsletter">
       <div width="100%" class="container">
         <div width="100%" class="row justify-content-center">
           <div class="col-lg-8">
             
            <div width="100%" id="login-box">
          <div class="left">
            
            <form action="{% url 'accounts:reset-eToken-action' %}" method="post">
              <label>Enter the 6-digit code sent to <i style="color:blue;">{{email_id}}</i></label>
                {% csrf_token %}
                
                <input type="hidden" name="email_id" value="{{email_id}}">
                <label>Don't see the email?</label>
                <button type="submit" class="btn btn-link">Send new code</button>

            </form>

            <p>Enter your OTP code to continue.</p>
            <form action="{% url 'accounts:eToken-action' %}" method="POST">
              {% csrf_token %} 
              <input type="hideen" name='email_id' id="email_id" value ="{{email_id}}"/>
              <input type="number" name='eToken' id="eToken" onKeyPress="if(this.value.length==6) return false;" required/>
              <button class="social-signin google" type="submit" name='submit'  id="submit" value="Submit"  style="background-color: #106eea;">Submit</button>
            </form>
            
          </div>
    
   <div class="right" style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
      <div style="margin-top: 130px;">
       <h2 style="font-size: 15px; color:#fff;">One-Time Passcode Verification (OTP)</h2>
       
    </div>
     
   
 </div>
 
             
           </div>
         </div>
       </div>
     </div>
 </div>
 
{% endblock %}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/employer_signup.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    {{title}} 
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer"  >
    <div width="100%" class="footer-newsletter">
       <div width="100%" class="container">
         <div width="100%" class="row justify-content-center">
           <div class="col-lg-6">
             <h4>Create an Employer Account on JobFinder</h4>
             <p>Get the right candidates for your open positions</p>
             
             <form action="{% url 'accounts:signup-action' %}" method="POST">
              {% csrf_token %}
               <div width="100%" id="login-box">
            <div class="left">
                  <h1>Sign up</h1>
                  <input type="hideen" name="user_type" value="200"/>
                  <input type="text" name='first_name' id="first_name" placeholder="First Name" />
                  <input type="text" name='last_name' id="last_name" placeholder="Last Name" />
                  <input type="text" name='email_id' id="email_id" placeholder="E-mail" />
                  <input type="number" name='phone_number' id="phone" placeholder="Phone" onKeyPress="if(this.value.length==11) return false;"/>
                  <input type="password" name='password' id="password" placeholder="Password" />
                  <input type="password" name='confirm_password' id="password" placeholder="Confirm Password" />
                  <input type="checkbox" name='is_accept_tcs' id="tcs" value="1"/>
                  <label for="tcs">I accept the <u>Ts & Cs</u></label><br>
 
  <button class="social-signin google" type="submit" name='submit'  id="submit" value="Submit"  style="background-color: #106eea;">Submit</button>
  <p style="font-size: 12px;">If you have an account aready; <a href="{% url 'accounts:login' %}">Login here</a></p>
   </div>
    
   <div class="right" style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
    <div style="margin-top: 130px;">
       <h2 style="font-size: 25px; color:#fff;">You are welcome!</h2>
    
   <p style="font-size: 18px; color:#fff;">Feel free to signup with us</p> 
    </div>
     
   
 </div>
 
             </form>
           </div>
         </div>
       </div>
     </div>
 </div>
 
{% endblock %}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/jobseeker_signup.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    {{title}} 
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer"  >
    <div width="100%" class="footer-newsletter">
       <div width="100%" class="container">
         <div width="100%" class="row justify-content-center">
           <div class="col-lg-6">
             <h4>Create a Job seeker Account on JobFinder</h4>
             <p></p>
             
             <form action="{% url 'accounts:signup-action' %}" method="POST">
              {% csrf_token %} 
              <div width="100%" id="login-box">
   <div class="left">
     <h1>Sign up</h1>
     
     <input type="hideen" name="user_type" value="300"/>
                  <input type="text" name='first_name' id="first_name" placeholder="First Name" />
                  <input type="text" name='last_name' id="last_name" placeholder="Last Name" />
                  <input type="text" name='email_id' id="email_id" placeholder="E-mail" />
                  <input type="number" name='phone_number' id="phone" placeholder="Phone" onKeyPress="if(this.value.length==11) return false;" />
                  <input type="password" name='password' id="password" placeholder="Password" />
                  <input type="password" name='confirm_password' id="password" placeholder="Confirm Password" />
                  <input type="checkbox" name='is_accept_tcs' id="tcs" value="1"/>
                  <label for="tcs">I accept the <u>Ts & Cs</u></label><br>
 
  <button class="social-signin google" type="submit" name='submit'  id="submit" value="Submit"  style="background-color: #106eea;">Submit</button>
  <p style="font-size: 12px;">If you have an account aready; <a href="{% url 'accounts:login' %}">Login here</a></p>
   </div>
    
   <div class="right" style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
    <div style="margin-top: 130px;">
       <h2 style="font-size: 25px; color:#fff;">You are welcome!</h2>
    
   <p style="font-size: 18px; color:#fff;">Feel free to signup with us</p> 
    </div>
     
   
 </div>
 
             </form>
           </div>
         </div>
       </div>
     </div>
 </div>
 
{% endblock %}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    Login
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer">
    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Login</h4>
  
            <form action="{% url 'accounts:login-action' %}" method="POST" class="form-group" width="100%">
              {% csrf_token %}
              <div id="login-box">
  
                <div class="right">
                  <div class="right"
                    style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
                    <div style="margin-top: 130px;">
                      <h2 style="font-size: 25px; color:#fff;">Not a member yet?</h2>
  
                      <p style="font-size: 17px; color:#fff;">Feel free to &nbsp;&nbsp;<a href="{% url 'accounts:signup' %}"
                          style="text-decoration: underline; color: white;">Sign up</a> with us</p>
                    </div>
  
  
                  </div>
  
                </div>
                <div class="left">
  
                  <h1>Sign in</h1>
  
  
                  <input type="text" name='email_id' placeholder="E-mail" />
                  <input type="password" name='password' placeholder="Password" />
  
  
                  <button class="social-signin google" type="submit" name='submit' value="Submit"
                    style="background-color: #106eea;">Submit</button>
  
                  <p style="font-size: 14px;">Forgot your password?&nbsp;&nbsp;<a href="{% url 'accounts:password-recovery' %}">Click here</a></p>
  
                </div>
  
                <div class="or">OR</div>
  
              </div>
  
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
 
{% endblock %}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/password_recovery.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    {{title}} 
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer"  >
    <div width="100%" class="footer-newsletter">
       <div width="100%" class="container">
         <div width="100%" class="row justify-content-center">
           <div class="col-lg-8">
           
             <p>Enter the email address for your JobFinder account below and we will email you a link to reset your password.</p>
             
             <form action="{% url 'accounts:password-recovery-action' %}" method="POST">
              {% csrf_token %}
               <div width="100%" id="login-box">
   <div class="left">
     <p>Enter your email to continue.</p>
     
     <input type="text" name='email_id' id="email_id" placeholder="E-mail" required />
    
 
  <button class="social-signin google" type="submit" name='submit'  id="submit" value="Submit"  style="background-color: #106eea;">Submit</button>
  <p style="font-size: 12px;">Remember password; <a href="{% url 'accounts:login' %}">Login here</a></p>
   </div>
    
   <div class="right" style="background: linear-gradient(60deg, #d476dd 20%,  #106eea 80.1%); text-align: center;">
    <div style="margin-top: 130px;">
       <h2 style="font-size: 25px; color:#fff;">Recover Password</h2>
    
   <!--<p style="font-size: 18px; color:#fff;">Feel free to signup with us</p>-->
    </div>
     
   
 </div>
 
             </form>
           </div>
         </div>
       </div>
     </div>
 </div>
 
{% endblock %}

{% block footer %}
{% endblock footer %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}
    {{title}} 
    {% endblock %}
{% block content %}
{% include 'accounts_css.html' %}
<div id="footer" style="background: linear-gradient(60deg, #E7F1FD 20%,  #6610f2 80.1%);" >
  <div class="footer-newsletter">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-6">
          {% if sub %}
          Congrats, your email has been reactivated to receive job alert
          {% endif %}
          <h1>Create Account</h1>
              <div id="login-box">
                <div class="left">
                  <button class="social-signin twitter"><a href="{% url 'accounts:jobseeker-signup' %}"  style=" color:#fff;">Jobseeker</a></button>
                  <a href="{% url 'accounts:jobseeker-signup' %}">
                    <img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/null/external-job-seeker-resume-flaticons-lineal-color-flat-icons.png"  class="img-circle circle-border m-b-md"/>
                  </a>
                  <p>Are you looking for your dream job?
                    Create a unique career profile with Jobfinder</p>
                  
                </div>
                <div class="right">
                  <button class="social-signin google"><a href="{% url 'accounts:employer-signup' %}" style=" color:#fff;">Employer</a></button>
                  <a href="{% url 'accounts:employer-signup' %}">
                    <img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/64/null/external-employers-back-to-work-flaticons-lineal-color-flat-icons.png" class="img-circle circle-border m-b-md"/>
                  </a>
                  <p>Are you looking for quality candidates?
                    Advertise and search with Jobfinder </p>
                  
                </div>
                
              </div>
          <p style="font-size: 18px;">If you have an account aready; <a href="{% url 'accounts:login' %}">Login here</a></p>
        </div>
      </div>
    </div>
</div> 
{% endblock %}

{% block footer %}
{% endblock footer %}