accounts/urls.py
from django.urls import path
from accounts import views,views_employer, views_jobseeker
from subscriptions.views import verify_payment,initiate_payment
from django.views.generic import TemplateView


app_name='accounts'

urlpatterns = [
   
    path('sign-up',TemplateView.as_view(template_name='accounts/signup.html',extra_context={'title': 'Register'}),name="signup"),
    path('sign-in',TemplateView.as_view(template_name='accounts/login.html',extra_context={'title': 'Signin'}),name="login"),
    path('eToken',TemplateView.as_view(template_name='accounts/eToken.html',extra_context={'title': 'eToken'}),name="eToken"),
    path('password-recovery',TemplateView.as_view(template_name='accounts/password_recovery.html',extra_context={'title': 'Password Recovery'}),name="password-recovery"),
    path('jobseeker/sign-up',TemplateView.as_view(template_name='accounts/jobseeker_signup.html',extra_context={'title': 'Jobseeker Account'}),name="jobseeker-signup"),
    path('employer/sign-up',TemplateView.as_view(template_name='accounts/employer_signup.html',extra_context={'title': 'Employer Account'}),name="employer-signup"),
    path('change-password/<int:id>', views.change_password, name='change-password'),

    #Jobseeker
    path('jobseeker/dashboard', views_jobseeker.JobSeekerHomeView.as_view(), name='jobseeker-home'),
    path('jobseeker/manage-jobs', views_jobseeker.manage_job, name='jobseeker-job-manager'),
    path('jobseeker/settings', views_jobseeker.settings, name='jobseeker-settings'),
    path('jobseeker/settings/update', views_jobseeker.update_settings, name='jobseeker-settings-update'),
    path('jobseeker/security', views_jobseeker.security, name='jobseeker-security'),
    path('jobseeker/security/password-update', views_jobseeker.update_password, name='jobseeker-password-update'),
    path('jobseeker/security/username-update', views_jobseeker.update_username, name='jobseeker-username-update'),
    path('jobseeker/notifications', views_jobseeker.notification, name='jobseeker-notification'),
    path('jobseeker/<int:pk>/delete', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/delete/', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/avater-updated', views_jobseeker.update_avater, name='jobseeker-avater-update'),
    path('jobseeker/avater-removed', views_jobseeker.remove_avater, name='jobseeker-avater-remove'),
    path('jobseeker/resume',views_jobseeker.upload_cv,name='jobseeker-upload-cv'),
    path('jobseeker/resume-update',views_jobseeker.update_cv,name='jobseeker-cv-update'),
    path('jobseeker/feedback',views_jobseeker.jobseeker_feedback,name='jobseeker-feedback'),
    path('jobseeker/feedback/sent',views_jobseeker.jobseeker_feedback_save,name='jobseeker-feedback-action'),
    
    
    #Employer
    path('employer/listing/direct', views_employer.direct_job, name='employer-direct-job'),
    path('employer/listing/featured', views_employer.indirect_job, name='employer-indirect-job'),
    path('employer/applicant/view', views_employer.applicants, name='employer-job-applicants'),
    path('employer/dashboard',views_employer.dashboard, name='employer-home'),
    path('employer/profile',views_employer.settings, name='employer-settings'),
    path('employer/profile/update',views_employer.update_settings, name='employer-settings-update'),
    path('employer/logo/update',views_employer.update_logo, name='employer-logo-update'),
    path('employer/logo/remove',views_employer.remove_logo, name='employer-logo-remove'),
    path('employer/billings', views_employer.billing, name='employer-billing'),
    path('employer/security', views_employer.security, name='employer-security'),
    path('employer/security/password/update', views_employer.update_password, name='employer-password-update'),
    path('employer/security/username/update', views_employer.update_username, name='employer-username-update'),
    path('employer/notifications', views_employer.notification, name='employer-notification'),
    path('employer/feedback',views_employer.employer_feedback,name='employer-feedback'),
    path('employer/feedback/sent',views_employer.employer_feedback_save,name='employer-feedback-action'),
    path('employer/delete', views_employer.delete_account, name='employer-delete-account'),
    path('employer/payment/initiate',initiate_payment, name='employer-initiate-payment'),
    path('<str:ref>/',verify_payment,name="verify-payment"),
    
    
    
    # actions 
    path('sign-up/do', views.signup_action, name='signup-action'),
    path('eToken-validation', views.eToken_action, name='eToken-action'),
    path('eToken/reset', views.reset_eToken_action, name='reset-eToken-action'),
    path('password/reset', views.password_recovery_action, name='password-recovery-action'),
    path('password/change', views.change_password_action, name='change-password-action'),
    path('login/do', views.login_action, name='login-action'),
    path('logout', views.logout_user_action, name='logout'),
    
    
    
    
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from accounts import views_admin

urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('subscriptions/', include('subscriptions.urls',namespace='subscriptions')),
    path('', include('main.urls',namespace='main')),
    path('', include('listings.urls',namespace='listings')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
    
    # Employer
    path('jf-admin/employers',views_admin.employer_list,name='admin-employers'),
    path('jf-admin/employers/<slug:slug>/profile', views_admin.employer_profile, name="employer-profile"),
    path('jf-admin/employers/<slug:slug>/payments', views_admin.employer_payments, name="employer-payments"),
    path('jf-admin/employers/<str:ref>/verify-a-payment', views_admin.verify_payment_page, name="verify-payment-page"),
    path('jf-admin/employers/<str:ref>/verified', views_admin.verify_payment, name="verify-payment"),
   
    
    path('jf-admin/manage/listing',views_admin.manage_job, name='admin-manage-listing'),
    path('jf-admin/manage/listing/<slug:slug>/delete',views_admin.delete_job, name='admin-delete-listing'),
    
    # Jobseekr
    path('jf-admin/jobseekers',views_admin.jobseeker_list,name='admin-jobseekers'),
    path('jf-admin/jobseekers/<slug:slug>/profile', views_admin.jobseeker_profile, name="jobseeker-profile"),
    
   
    path('jf-admin/create-newsletter', views_admin.create_newsletter, name='create-newsletter'),
    path('jf-admin/newsletter-view', views_admin.newsletter_view, name='newsletter-view'),
    path('jf-admin/send-newsletter', views_admin.newsletter_action, name='newsletter-action'),
    path('jf-admin/newsletter/<slug:slug>/view', views_admin.newsletter_update_view, name='newsletter-update-view'),
    path('jf-admin/newsletter/<slug:slug>/update',views_admin.newsletter_update_action,name='newsletter-update-action'),
    path('jf-admin/newsletter/<slug:slug>/delete',views_admin.delete_newsletter,name='admin-delete-newsletter'),
    path('jf-admin/newsletter/subscriber-view', views_admin.newsletter_subscriber_view, name='newsletter-subscriber-view'),
    path('jf-admin/newsletter/subscriber/<slug:slug>/delete',views_admin.delete_newsletter_subscriber,name='admin-delete-newsletter-subscriber'),
    
    path('jf-admin/accounts-view',views_admin.manage_user,name='admin-manage-user'),
    path('jf-admin/account/<slug:slug>/view',views_admin.manage_user_update_view,name='admin-manage-user-update-view'),
    path('jf-admin/account/<slug:slug>/update',views_admin.manage_user_update,name='admin-manage-user-update'),
    path('jf-admin/account/<slug:slug>/delete',views_admin.delete_user,name='admin-delete-user'),
    

    # Admin-utilities
    path('jf-admin-create-admin',views_admin.create_admin,name='create-admin'),
    path('jf-admim-reset-password',TemplateView.as_view(template_name = "accounts/admin/reset_password.html",extra_context={'title': 'Jobfinder-Administrator-Reset-Password'}), name='admin-reset-password-view'),
    path('jf-admin-delete-admin-account',views_admin.delete_admin_account,name='delete-admin-account'),
    path('jf-admin-delete-users-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin-reset-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin',TemplateView.as_view(template_name = "accounts/admin/login.html",extra_context={'title': 'Jobfinder-Administrator-Login'}), name='login-admin'),
    path('jf-admin/login',views_admin.login_admin_action,name='login-admin-action'),
    path('jf-admin/dashboard',views_admin.AdminHomeView.as_view(), name='admin-home'),
    path('jf-admin/password/changed',views_admin.reset_password_action,name='admin-reset-password-action'),
    path('jf-admin/logout',views_admin.logout_admin,name='logout-admin'),
    path('e-404/',TemplateView.as_view(template_name='404.html',extra_context={'title': 'E404'}),name="404"),

    
  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'accounts.views.custom_page_not_found_view'
handler500 = 'accounts.views.custom_error_view'
handler403 = 'accounts.views.custom_permission_denied_view'
handler400 = 'accounts.views.custom_bad_request_view'

listings/urls.py
from django.urls import path,include
from listings import views


app_name='listings'

urlpatterns = [
  
    
    path('', views.JobListView.as_view(), name='home'),
    path('create-job',views.create_job_View,name='job-form'),
    path('post-job',views.create_job_action,name='post-job'),
    path('<slug:slug>/', views.job_detail, name="job-detail" ),
    path('<slug:slug>/application/', views.application_form, name="application-form" ),
    path('<slug:slug>/apply/', views.apply, name="apply"),
    path('<slug:slug>/edit/', views.job_form_update_view, name="job-update" ),
    path('<slug:slug>/update/', views.update_job, name="update-job" ),
    path('<slug:slug>/delete/', views.delete_job, name="delete-job" ),
   
    
    path('search-job-location', views.search_job_by_location, name="search-job-location" ),
    path('search-job-location-keyword', views.search_job_by_location_keyword, name="search-job-location-keyword" ),
   
 
 
    path('free-job-postings', views.FreeJobPostPageView.as_view(), name='free-job-post'),
    path('featured-job-posting', views.FeaturedJobPostingPageView.as_view(), name='featured-job-posting'),
    
    
    
    

   
]

main/urls.py
from django.urls import path
from . import views


app_name='main'

urlpatterns = [

    path('recuirtments', views.TemplateView.as_view(template_name = "main/recruitment.html",extra_context={'title': 'Recruitment Company in Nigeria'}), name='recruitments'),
    path('employers', views.employer_page, name='employers'),
    path('find-candidates', views.FindCandidatesView.as_view(), name='find-candidates'),
    path('contact', views.contact, name='contact'),
    path('help', views.help_view, name='help-view'),
    path('subscribe-to-a-newsletter', views.subscribe_to_a_newsletter, name='subscribe-to-a-newsletter'),
    
    
     
]

templates/accounts_css.html
<style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,500);
  *:focus {
  outline: none;
  }

  body {
  margin: 0;
  padding: 0;
  background: #DDD;
  font-size: 16px;
  color: #222;
  font-family: 'Roboto', sans-serif;
  font-weight: 300;
  }

  #login-box {
  position: relative;
  margin: 5% auto;
  width: 600px;
  height: 400px;
  background: #FFF;
  border-radius: 2px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
  }
  @media only screen and (max-width: 768px) {
  /* For mobile phones: */
  #login-box {
  width: 100%;
  height: 700px;
  }
  }
  .left {
  position: absolute;
  top: 0;
  left: 0;
  box-sizing: border-box;
  padding: 40px;
  width: 300px;
  height: 400px;
  }

  h1 {
  margin: 0 0 20px 0;
  font-weight: 300;
  font-size: 28px;
  }

  
  input[type="hideen"] {
  display: none;
  }

  input[type="text"],
  input[type="tel"],
  input[type="number"],
  input[type="password"] {
  display: block;
  box-sizing: border-box;
  margin-bottom: 10px;
  padding: 4px;
  width: 220px;
  height: 32px;
  border: none;
  border-bottom: 1px solid #AAA;
  font-family: 'Roboto', sans-serif;
  font-weight: 400;
  font-size: 15px;
  transition: 0.2s ease;
  }

  input[type="text"]:focus,
  input[type="password"]:focus {
  border-bottom: 2px solid #16a085;
  color: #16a085;
  transition: 0.2s ease;
  }

  input[type="submit"] {
  margin-top: 28px;
  width: 120px;
  height: 32px;
  background: #16a085;
  border: none;
  border-radius: 2px;
  color: #FFF;
  font-family: 'Roboto', sans-serif;
  font-weight: 500;
  text-transform: uppercase;
  transition: 0.1s ease;
  cursor: pointer;
  }

  input[type="submit"]:hover,
  input[type="submit"]:focus {
  opacity: 0.8;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
  transition: 0.1s ease;
  }

  input[type="submit"]:active {
  opacity: 1;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
  transition: 0.1s ease;
  }
  @media only screen and (max-width: 768px){
  .or{
      margin-top: 190px;
      top: 0px;
      
      text-align: center;
      
  }
  }
  .or {
  position: absolute;
  top: 180px;
  left: 280px;
  width: 40px;
  height: 40px;
  background: #DDD;
  border-radius: 50%;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
  line-height: 40px;
  text-align: center;
  }

  .right {
  position: absolute;
  top: 0;
  right: 0;
  box-sizing: border-box;
  padding: 40px;
  width: 300px;
  height: 400px;
  background: url('https://goo.gl/YbktSj');
  background-size: cover;
  background-position: center;
  border-radius: 0 2px 2px 0;
  }

  .right .loginwith {
  display: block;
  margin-bottom: 40px;
  font-size: 28px;
  color: #FFF;
  text-align: center;
  }
  @media only screen and (max-width: 768px) {
  /* For mobile phones: */
  .right {
  margin-top: 360px;
  }
  }
  button.social-signin {
  margin-bottom: 20px;
  width: 220px;
  height: 36px;
  border: none;
  border-radius: 2px;
  color: #FFF;
  font-family: 'Roboto', sans-serif;
  font-weight: 500;
  transition: 0.2s ease;
  cursor: pointer;
  }

  button.social-signin:hover,
  button.social-signin:focus {
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.4);
  transition: 0.2s ease;
  }

  button.social-signin:active {
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
  transition: 0.2s ease;
  }

  button.social-signin.facebook {
  background: #32508E;
  }

  button.social-signin.twitter {
  background: #55ACEE;
  }

  button.social-signin.google {
  background: #DD4B39;
  }
</style>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  
  <title>{% block title %}{% endblock title %} | Job Finder</title>
  
  <meta content="{{job.seo_description}}" name="description">
  <meta content="{{job.seo_keywords}}" name="keywords">

 <!-- Favicons -->
 <link href="{% static 'main/assets/img/favicoon.png' %}" rel="icon">
 <link href="{% static 'main/assets/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  {% block css %}
  <!-- Vendor CSS Files -->
  <link href="{% static 'main/assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'main/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'main/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  {% endblock css %}
  
  {% block main_css %}
  <!-- Template Main CSS File -->
  <link href="{% static 'main/assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'main/assetss/css/style.css' %}" rel="stylesheet">
  {% endblock main_css %}
  
  
</head>

<body>
  {% comment %} {% if messages %}
<div class="col-12">
   {% for message in messages %}
   {% if message.tags == "error" %}
   <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
      <b>{{ message }}</b>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
   </div>
   {% elif message.tags == "success" %}
   <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
    <b>{{ message }}</b>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
 </div>
   {% endif %}
   {% endfor %}
</div>
{% endif %} {% endcomment %}

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
        <i class="bi bi-envelope d-flex align-items-center"><a href="mailto:jfinder@placement-hub.com">jfinder@placement-hub.com</a></i>
        <i class="bi bi-phone d-flex align-items-center ms-4"><span>+234 807 244 5395</span></i>
      </div>
      <div class="social-links d-none d-md-flex align-items-center">
        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <!--<h1 class="logo"><a href="index.html">JobFInder<span>.</span></a></h1>
       Uncomment below if you prefer to use an image logo -->
       <a href="{% url 'listings:home' %}" class="logo"><img src="{% static 'main/assets/img/heroL.png' %}" alt=""></a>
      {% block navbar %}
      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'main:employers' %}" style="color: #106eea;">Employers</a></li>
          <!--<li><a class="nav-link scrollto" href="{% url 'listings:free-job-post' %}">Free Job Posting</a></li>-->
          <li><a class="nav-link scrollto" href="{% url 'listings:featured-job-posting' %}">Featured Job Posting</a></li>
          <li><a class="nav-link scrollto " href="{% url 'main:recruitments' %}">Recruitment</a></li>
          <li><a class="nav-link scrollto" href="{% url 'main:find-candidates' %}">Candidate Search</a></li>
          <!--<li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>-->
          {% if user.is_authenticated %}
            <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}" style="color: #106eea;">Logout</a></li>
            {% if request.session.is_employer %}
            <li><a class="nav-link scrollto" href="{% url 'accounts:employer-home' %}" style="color: #8110ea;">Dashboard</a></li>
            {% elif request.session.is_jobseeker %}
            <li><a class="nav-link scrollto" href="{% url 'accounts:jobseeker-home' %}" style="color: #8110ea;">Dashboard</a></li>
            {% elif request.session.is_admin  %}
            <li><a class="nav-link scrollto" href="{% url 'admin-home' %}" style="color: #8110ea;">Dashboard</a></li>
            {% endif %}
          {% else %}
          <li><a class="nav-link scrollto" href="{% url 'accounts:login' %}">Login</a></li>
          <li><a class="nav-link scrollto" href="{% url 'accounts:signup' %}" style="color: #106eea;">Sign Up</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->
      {% endblock navbar %}
    </div>
  </header><!-- End Header -->
  {% block content %}



  {% endblock content %}
  <!-- ======= Footer ======= -->
  {% block footer %}
  <footer id="footer" style="background: #fff;" >

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h4>Join Our Newsletter</h4>
            
            <form action="{% url 'main:subscribe-to-a-newsletter' %}" method="post">
              {% csrf_token %}
              <input type="email" name="email" required>
              <input type="submit" value="Subscribe">
            </form>

          </div>
        </div>
      </div>
    </div>

    <div class="footer-top" style="background: #fff;" >
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-contact">
            <h3> <a href="{% url 'listings:home' %}" class="logo"><img  height="40px" src="{% static 'main/assets/img/heroL.png' %}" alt=""></a><span>.</span></h3>
            <p>
              8 Adelabu Street,
              Alh. Masha Road<br>
              Surulere, Lagos. <br><br>
              <strong>Phone:</strong>   +234 807 244 5395<br><br>
              <strong>Email:</strong> jfinder@placement-hub.com<br>
            </p>
          </div>

          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:employers' %}">Employers</a></li>
              <!--<li><i class="bx bx-chevron-right"></i> <a href="{% url 'listings:free-job-post' %}">Free Job Posting</a></li>-->
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'listings:featured-job-posting' %}">Featured Job Posting</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:recruitments' %}">Recruitment</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'main:find-candidates' %}">Candidate Search</a></li>
            </ul>
          </div>

       
          <div class="col-lg-4 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
            <p>Checkout our lastest post on socials.  </p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
          </div>

        </div>
      </div>
    </div>

   
  </footer><!-- End Footer -->
  {% endblock footer%}
  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  {% block js  %}
  <!-- Vendor JS Files -->
  <script src="{% static 'main/assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'main/assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'main/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'main/assets/vendor/waypoints/noframework.waypoints.js' %}"></script>
  <script src="{% static 'main/assets/vendor/php-email-form/validate.js' %}"></script>
  {% endblock js  %}
  <!-- Template Main JS File -->
  <script src="{% static 'main/assets/js/main.js' %}"></script>
   
  <!--sweet alert-->
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script>
    {% for message in messages %}
    {% if message.tags == "error" %}
    swal("Error!", '{{ message }}', "error");
    fire('{{ message }}', "error")
    {% else %}
    swal("Bravo!", '{{ message }}', "success");
    {% endif %}
    {% endfor %}
</script>
<script>
  
</script>
</body>

</html>

templates/breadcrumb_right_sidebar.html
<div class="col-5">
    <h4 class="page-title">Dashboard</h4>
    <div class="d-flex align-items-center">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'accounts:employer-home' %}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'accounts:employer-direct-job' %}">Direct Listing</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'accounts:employer-indirect-job' %}">Featured Listing</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'accounts:employer-job-applicants' %}">Applicants</a></li>
            </ol>
        </nav>
    </div>
</div>