accounts/urls.py
from django.urls import path
from accounts import views,views_employer, views_jobseeker
from subscriptions.views import verify_payment,initiate_payment
from django.views.generic import TemplateView


app_name='accounts'

urlpatterns = [
   
    path('sign-up',TemplateView.as_view(template_name='accounts/signup.html',extra_context={'title': 'Register'}),name="signup"),
    path('sign-in',TemplateView.as_view(template_name='accounts/login.html',extra_context={'title': 'Signin'}),name="login"),
    path('eToken',TemplateView.as_view(template_name='accounts/eToken.html',extra_context={'title': 'eToken'}),name="eToken"),
    path('password-recovery',TemplateView.as_view(template_name='accounts/password_recovery.html',extra_context={'title': 'Password Recovery'}),name="password-recovery"),
    path('jobseeker/sign-up',TemplateView.as_view(template_name='accounts/jobseeker_signup.html',extra_context={'title': 'Jobseeker Account'}),name="jobseeker-signup"),
    path('employer/sign-up',TemplateView.as_view(template_name='accounts/employer_signup.html',extra_context={'title': 'Employer Account'}),name="employer-signup"),
    path('change-password/<int:id>', views.change_password, name='change-password'),

    #Jobseeker
    path('jobseeker/dashboard', views_jobseeker.JobSeekerHomeView.as_view(), name='jobseeker-home'),
    path('jobseeker/manage-jobs', views_jobseeker.manage_job, name='jobseeker-job-manager'),
    path('jobseeker/settings', views_jobseeker.settings, name='jobseeker-settings'),
    path('jobseeker/settings/update', views_jobseeker.update_settings, name='jobseeker-settings-update'),
    path('jobseeker/security', views_jobseeker.security, name='jobseeker-security'),
    path('jobseeker/security/password-update', views_jobseeker.update_password, name='jobseeker-password-update'),
    path('jobseeker/security/username-update', views_jobseeker.update_username, name='jobseeker-username-update'),
    path('jobseeker/notifications', views_jobseeker.notification, name='jobseeker-notification'),
    path('jobseeker/<int:pk>/delete', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/delete/', views_jobseeker.delete_account, name='jobseeker-delete-account'),
    path('jobseeker/avater-updated', views_jobseeker.update_avater, name='jobseeker-avater-update'),
    path('jobseeker/avater-removed', views_jobseeker.remove_avater, name='jobseeker-avater-remove'),
    path('jobseeker/resume',views_jobseeker.upload_cv,name='jobseeker-upload-cv'),
    path('jobseeker/resume-update',views_jobseeker.update_cv,name='jobseeker-cv-update'),
    path('jobseeker/feedback',views_jobseeker.jobseeker_feedback,name='jobseeker-feedback'),
    path('jobseeker/feedback/sent',views_jobseeker.jobseeker_feedback_save,name='jobseeker-feedback-action'),
    
    
    #Employer
    path('employer/listing/direct', views_employer.direct_job, name='employer-direct-job'),
    path('employer/listing/featured', views_employer.indirect_job, name='employer-indirect-job'),
    path('employer/applicant/view', views_employer.applicants, name='employer-job-applicants'),
    path('employer/dashboard',views_employer.dashboard, name='employer-home'),
    path('employer/profile',views_employer.settings, name='employer-settings'),
    path('employer/profile/update',views_employer.update_settings, name='employer-settings-update'),
    path('employer/logo/update',views_employer.update_logo, name='employer-logo-update'),
    path('employer/logo/remove',views_employer.remove_logo, name='employer-logo-remove'),
    path('employer/billings', views_employer.billing, name='employer-billing'),
    path('employer/security', views_employer.security, name='employer-security'),
    path('employer/security/password/update', views_employer.update_password, name='employer-password-update'),
    path('employer/security/username/update', views_employer.update_username, name='employer-username-update'),
    path('employer/notifications', views_employer.notification, name='employer-notification'),
    path('employer/feedback',views_employer.employer_feedback,name='employer-feedback'),
    path('employer/feedback/sent',views_employer.employer_feedback_save,name='employer-feedback-action'),
    path('employer/delete', views_employer.delete_account, name='employer-delete-account'),
    path('employer/payment/initiate',initiate_payment, name='employer-initiate-payment'),
    path('<str:ref>/',verify_payment,name="verify-payment"),
    
    
    
    # actions 
    path('sign-up/do', views.signup_action, name='signup-action'),
    path('eToken-validation', views.eToken_action, name='eToken-action'),
    path('eToken/reset', views.reset_eToken_action, name='reset-eToken-action'),
    path('password/reset', views.password_recovery_action, name='password-recovery-action'),
    path('password/change', views.change_password_action, name='change-password-action'),
    path('login/do', views.login_action, name='login-action'),
    path('logout', views.logout_user_action, name='logout'),
    
    
    
    
    
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from accounts import views_admin

urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('subscriptions/', include('subscriptions.urls',namespace='subscriptions')),
    path('', include('main.urls',namespace='main')),
    path('', include('listings.urls',namespace='listings')),
    #path('ckeditor/', include('ckeditor_uploader.urls')),
    
    # Employer
    path('jf-admin/employers',views_admin.employer_list,name='admin-employers'),
    path('jf-admin/employers/<slug:slug>/profile', views_admin.employer_profile, name="employer-profile"),
    path('jf-admin/employers/<slug:slug>/payments', views_admin.employer_payments, name="employer-payments"),
    path('jf-admin/employers/<str:ref>/verify-a-payment', views_admin.verify_payment_page, name="verify-payment-page"),
    path('jf-admin/employers/<str:ref>/verified', views_admin.verify_payment, name="verify-payment"),
   
    
    path('jf-admin/manage/listing',views_admin.manage_job, name='admin-manage-listing'),
    path('jf-admin/manage/listing/<slug:slug>/delete',views_admin.delete_job, name='admin-delete-listing'),
    
    # Jobseekr
    path('jf-admin/jobseekers',views_admin.jobseeker_list,name='admin-jobseekers'),
    path('jf-admin/jobseekers/<slug:slug>/profile', views_admin.jobseeker_profile, name="jobseeker-profile"),
    
   
    path('jf-admin/create-newsletter', views_admin.create_newsletter, name='create-newsletter'),
    path('jf-admin/newsletter-view', views_admin.newsletter_view, name='newsletter-view'),
    path('jf-admin/send-newsletter', views_admin.newsletter_action, name='newsletter-action'),
    path('jf-admin/newsletter/<slug:slug>/view', views_admin.newsletter_update_view, name='newsletter-update-view'),
    path('jf-admin/newsletter/<slug:slug>/update',views_admin.newsletter_update_action,name='newsletter-update-action'),
    path('jf-admin/newsletter/<slug:slug>/delete',views_admin.delete_newsletter,name='admin-delete-newsletter'),
    path('jf-admin/newsletter/subscriber-view', views_admin.newsletter_subscriber_view, name='newsletter-subscriber-view'),
    path('jf-admin/newsletter/subscriber/<slug:slug>/delete',views_admin.delete_newsletter_subscriber,name='admin-delete-newsletter-subscriber'),
    
    path('jf-admin/accounts-view',views_admin.manage_user,name='admin-manage-user'),
    path('jf-admin/account/<slug:slug>/view',views_admin.manage_user_update_view,name='admin-manage-user-update-view'),
    path('jf-admin/account/<slug:slug>/update',views_admin.manage_user_update,name='admin-manage-user-update'),
    path('jf-admin/account/<slug:slug>/delete',views_admin.delete_user,name='admin-delete-user'),
    

    # Admin-utilities
    path('jf-admin-create-admin',views_admin.create_admin,name='create-admin'),
    path('jf-admim-reset-password',TemplateView.as_view(template_name = "accounts/admin/reset_password.html",extra_context={'title': 'Jobfinder-Administrator-Reset-Password'}), name='admin-reset-password-view'),
    path('jf-admin-delete-admin-account',views_admin.delete_admin_account,name='delete-admin-account'),
    path('jf-admin-delete-users-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin-reset-accounts',views_admin.delete_users_accounts,name='delete-users-accounts'),
    path('jf-admin',TemplateView.as_view(template_name = "accounts/admin/login.html",extra_context={'title': 'Jobfinder-Administrator-Login'}), name='login-admin'),
    path('jf-admin/login',views_admin.login_admin_action,name='login-admin-action'),
    path('jf-admin/dashboard',views_admin.AdminHomeView.as_view(), name='admin-home'),
    path('jf-admin/password/changed',views_admin.reset_password_action,name='admin-reset-password-action'),
    path('jf-admin/logout',views_admin.logout_admin,name='logout-admin'),
    path('e-404/',TemplateView.as_view(template_name='404.html',extra_context={'title': 'E404'}),name="404"),

    
  
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'accounts.views.custom_page_not_found_view'
handler500 = 'accounts.views.custom_error_view'
handler403 = 'accounts.views.custom_permission_denied_view'
handler400 = 'accounts.views.custom_bad_request_view'

listings/urls.py
from django.urls import path,include
from listings import views


app_name='listings'

urlpatterns = [
  
    
    path('', views.JobListView.as_view(), name='home'),
    path('create-job',views.create_job_View,name='job-form'),
    path('post-job',views.create_job_action,name='post-job'),
    path('<slug:slug>/', views.job_detail, name="job-detail" ),
    path('<slug:slug>/application/', views.application_form, name="application-form" ),
    path('<slug:slug>/apply/', views.apply, name="apply"),
    path('<slug:slug>/edit/', views.job_form_update_view, name="job-update" ),
    path('<slug:slug>/update/', views.update_job, name="update-job" ),
    path('<slug:slug>/delete/', views.delete_job, name="delete-job" ),
   
    
    path('search-job-location', views.search_job_by_location, name="search-job-location" ),
    path('search-job-location-keyword', views.search_job_by_location_keyword, name="search-job-location-keyword" ),
   
 
 
    path('free-job-postings', views.FreeJobPostPageView.as_view(), name='free-job-post'),
    path('featured-job-posting', views.FeaturedJobPostingPageView.as_view(), name='featured-job-posting'),
    
    
    
    

   
]

accounts/forms.py
from django.forms import ModelForm
from accounts.models import *
from django.utils.translation import gettext_lazy as _


class NotificationEmployerForm(ModelForm):
    
    class Meta:
        model= Employer
        fields= ['subscribed_to_newsletter',]

        labels = {
            'subscribed_to_newsletter': _('Newsletter'),
        
            }

        
class NotificationJobSeekerForm(ModelForm):
    
    class Meta:
        model= JobSeeker
        fields= ['subscribed_to_newsletter',]
       

accounts/templates/accounts/jobseeker/dashboard.html
{% extends 'dashboard_base.html' %}
{% load static %}
    {% block title %}
       {{title}}
    {% endblock %}

    {% comment %} {% block breadcrumb_right_sidebar %}

    {% endblock breadcrumb_right_sidebar %} {% endcomment %}

    {% block content %}
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                
                <div class="row">
                    <!-- column -->
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <!-- title -->
                                <div class="d-md-flex">
                                    <div>
                                        <h5 class="card-subtitle">Overview of Top Listing jobs</h5>
                                    </div>
                                    <div class="ms-auto">
                                        <div class="dl">
                                            <select class="form-select shadow-none">
                                                <option value="0" selected>Monthly</option>
                                                <option value="1">Daily</option>
                                                <option value="2">Weekly</option>
                                                <option value="3">Yearly</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <!-- title -->
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- column -->
                    <div class="row">
                        <!-- column -->
                        {% for job in jobs  %}
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="comment-widgets scrollable">
                                    <!-- Comment Row --> 
                                    <div class="d-flex flex-row comment-row m-t-0">
                                        <div class="p-2"><a href="{% url 'listings:job-detail' job.slug  %}"><img src="{{job.logo.url}}" alt="user" width="80"
                                                class="rounded-circle"></a></div>
                                        <div class="comment-text w-100">
                                            
                                            <h6 class="font-medium"><a href="{% url 'listings:job-detail' job.slug  %}">{{job.title|title|urlize}}</a></h6>
                                            <span class="m-b-15 d-block">{{job.description|truncatewords:20}} </span>
                                            <div class="comment-footer">
                                                <span class="text-muted float-end">{{job.created_at|timesince}}</span> 
                                                
                                                <span class="label label-rounded label-primary">{{job.type}}</span> 
                                                   
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Comment Row ends --> 
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <!-- column -->
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
    {% endblock %}

accounts/templates/accounts/jobseeker/security.html
{% extends 'dashboard_base.html' %}
{% load static %}
    {% block title %}
       {{title}}
    {% endblock %}


        {% block content %}
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-xl px-4 mt-4">

                <hr class="mt-0 mb-4">
                <div class="row">
                    <div class="col-lg-2">
                    </div>
                    <div class="col-lg-8">
        
                        <div class="card mb-4">
                            <div class="card-header">Change Password</div>
                            <div class="card-body">
                                <form method="post" action="{% url 'accounts:jobseeker-password-update' %}">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <label class="small mb-1" for="newPassword">New Password</label>
                                        <input class="form-control" id="newPassword" name="new_password"type="password"
                                            placeholder="Enter new password" required>
                                    </div>
        
                                    <div class="mb-3">
                                        <label class="small mb-1" for="confirmPassword">Confirm Password</label>
                                        <input class="form-control" id="confirmPassword" name="confirm_password"type="password"
                                            placeholder="Confirm new password" required>
                                    </div>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </form>
                            </div>
                        </div>

                        <div class="card mb-4">
                            <div class="card-header">Change Username</div>
                            <div class="card-body">
                                <form method="post" action="{% url 'accounts:jobseeker-username-update' %}">
                                    <div class="mb-3">
                                        <label class="small mb-1" for="currentUsername">Username</label>
                                        <input class="form-control" id="currentUsername" name="username"type="text"
                                             value="{{user.username}}"readonly>
                                    </div>
        
                                    <div class="mb-3">
                                        <label class="small mb-1" for="newUsername">New Username</label>
                                        <input class="form-control" id="newUsername" name="new_username" type="text"
                                            placeholder="New username" required>
                                    </div>
                                    <button class="btn btn-primary" type="submit">Save</button>
                                </form>
                            </div>
                        </div>
        
                        <!--<div class="card mb-4">
                            <div class="card-header">Security Preferences</div>
                            <div class="card-body">
        
                                <h5 class="mb-1">Account Privacy</h5>
                                <p class="small text-muted">By setting your account to private, your profile information and
                                    posts will not be visible to users outside of your user groups.</p>
                                <form>
                                    <div class="form-check">
                                        <input class="form-check-input" id="radioPrivacy1" type="radio" name="radioPrivacy"
                                            checked="">
                                        <label class="form-check-label" for="radioPrivacy1">Public (posts are available to all
                                            users)</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" id="radioPrivacy2" type="radio" name="radioPrivacy">
                                        <label class="form-check-label" for="radioPrivacy2">Private (posts are available to only
                                            users in your groups)</label>
                                    </div>
                                </form>
                                <hr class="my-4">
        
                                <h5 class="mb-1">Data Sharing</h5>
                                <p class="small text-muted">Sharing usage data can help us to improve our products and better
                                    serve our users as they navigation through our application. When you agree to share usage
                                    data with us, crash reports and usage analytics will be automatically sent to our
                                    development team for investigation.</p>
                                <form>
                                    <div class="form-check">
                                        <input class="form-check-input" id="radioUsage1" type="radio" name="radioUsage"
                                            checked="">
                                        <label class="form-check-label" for="radioUsage1">Yes, share data and crash reports with
                                            app developers</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" id="radioUsage2" type="radio" name="radioUsage">
                                        <label class="form-check-label" for="radioUsage2">No, limit my data sharing with app
                                            developers</label>
                                    </div>
                                </form>
                            </div>
                        </div>-->
                    </div>
                    <div class="col-lg-2">
        
                        <!--<div class="card mb-4">
                            <div class="card-header">Two-Factor Authentication</div>
                            <div class="card-body">
                                <p>Add another level of security to your account by enabling two-factor authentication. We will
                                    send you a text message to verify your login attempts on unrecognized devices and browsers.
                                </p>
                                <form>
                                    <div class="form-check">
                                        <input class="form-check-input" id="twoFactorOn" type="radio" name="twoFactor"
                                            checked="">
                                        <label class="form-check-label" for="twoFactorOn">On</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" id="twoFactorOff" type="radio" name="twoFactor">
                                        <label class="form-check-label" for="twoFactorOff">Off</label>
                                    </div>
                                    <div class="mt-3">
                                        <label class="small mb-1" for="twoFactorSMS">SMS Number</label>
                                        <input class="form-control" id="twoFactorSMS" type="tel"
                                            placeholder="Enter a phone number" value="555-123-4567">
                                    </div>
                                </form>
                            </div>
                        </div>-->
                        
                        <!--Working uncomment when it's required -->
                        {% comment %} <div class="card mb-4">
                            <div class="card-header">Delete Account</div>
                            <div class="card-body">
                                <p>Deleting your account is a permanent action and cannot be undone. If you are sure you want to
                                    delete your account, select the button below.</p>
                                <form method="post" action="{% url 'accounts:jobseeker-delete-account' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger-soft text-danger" type="submit">I understand, delete my
                                        account</button>
                                </form>
                            </div>
                        </div> {% endcomment %}
                    </div>
                </div>
            </div>
            <style type="text/css">
                body {
                    margin-top: 20px;
                    background-color: #f2f6fc;
                    color: #69707a;
                }
        
                .img-account-profile {
                    height: 10rem;
                }
        
                .rounded-circle {
                    border-radius: 50% !important;
                }
        
                .card {
                    box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
                }
        
                .card .card-header {
                    font-weight: 500;
                }
        
                .card-header:first-child {
                    border-radius: 0.35rem 0.35rem 0 0;
                }
        
                .card-header {
                    padding: 1rem 1.35rem;
                    margin-bottom: 0;
                    background-color: rgba(33, 40, 50, 0.03);
                    border-bottom: 1px solid rgba(33, 40, 50, 0.125);
                }
        
                .form-control,
                .dataTable-input {
                    display: block;
                    width: 100%;
                    padding: 0.875rem 1.125rem;
                    font-size: 0.875rem;
                    font-weight: 400;
                    line-height: 1;
                    color: #69707a;
                    background-color: #fff;
                    background-clip: padding-box;
                    border: 1px solid #c5ccd6;
                    -webkit-appearance: none;
                    -moz-appearance: none;
                    appearance: none;
                    border-radius: 0.35rem;
                    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
                }
        
                .nav-borders .nav-link.active {
                    color: #0061f2;
                    border-bottom-color: #0061f2;
                }
        
                .nav-borders .nav-link {
                    color: #69707a;
                    border-bottom-width: 0.125rem;
                    border-bottom-style: solid;
                    border-bottom-color: transparent;
                    padding-top: 0.5rem;
                    padding-bottom: 0.5rem;
                    padding-left: 0;
                    padding-right: 0;
                    margin-left: 1rem;
                    margin-right: 1rem;
                }
        
                .btn-danger-soft {
                    color: #000;
                    background-color: #f1e0e3;
                    border-color: #f1e0e3;
                }
            </style>
            <script type="text/javascript">
        
            </script>

            <!-- ============================================================== -->
            <!-- End Container fluid  -->
        {% endblock %}

accounts/templates/accounts/jobseeker/upload_cv.html
{% extends 'dashboard_base.html' %}
{% load static %}
    {% block title %}
       {{title}}
    {% endblock %}


    {% block content %}
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                
                <div class="row">
                    <!-- column -->
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="col-lg-8 col-xlg-9 col-md-7">
                                    <div class="card">
                                        <div class="card-body">
                                            <form class="form-horizontal form-material mx-2" method="post" action="{% url 'accounts:jobseeker-cv-update' %}"  enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                    <label class="col-md-12">Upload CV</label>
                                                    <div class="col-md-12">
                                                        <input type="file" name="resume" value="{{ jobseeker.resume}}"
                                                            class="form-control form-control-line" required>
                                                    </div>
                                                    <p>{{ jobseeker.resume|filesizeformat }}</p>
                                                </div>
                            
                                                <div class="form-group">
                                                    <div class="col-sm-12">
                                                        <button  type="submit" class="btn btn-success text-white">Save</button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
            <!-- ============================================================== -->
            <!-- End Container fluid  -->
    {% endblock %}